name: CI
on:
  push:
    branches: [main,"feature/**"]
  pull_request:
    branches: [main]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
      - name: Set CI database URL
        run: echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/delevry_ci?schema=public" >> "$GITHUB_ENV"
      - run: npm run db:generate
      - run: npm run typecheck
      - run: npm run lint
      - run: npm test
      - run: npm run build